### ISSUE TITLE
Unauthorized error creating new connection

### ISSUE THREAD

**Issue by santoshauc** [microsoftgraph/msgraph-search-connector-sample#1]
I am getting below error even though I granted all the needed permission. Any help would be appreciated

Code: generalException
Message: {
  "error": {
    "code": "UnknownError",
    "message": "{\"code\":\"UnauthorizedAccess\",\"message\":\"Tenant unauthorized to access this API\"}",
    "innerError": {
      "request-id": "93729ccd-cad3-4725-8c49-c8fc6936bedf",
      "date": "2019-11-14T06:30:36"
    }
  }
}

Thanks

**Comment by sidhaw** [comment]
were you able to fix this ? getting the same error

**Comment by MatthewMcD** [comment]
Are you part of the Preview? It looks like your tenant isn't authorized.

> Important
>
>Microsoft Graph connectors and Microsoft Search APIs (query and index) are currently in preview status. To use connectors with Microsoft Search or to build connectors, you must sign up for the connectors preview program. To join the preview program, submit the Microsoft Graph connectors preview sign-up form.

**Comment by TekExpo** [comment]
I have signed up for connectors preview program, how much time does it take to process the request.
I am getting the same error as above.

**Comment by jasonjoh** [comment]
Correct, you need to be onboarded to the preview.
