### ISSUE TITLE
Creating a connection throws an error.

### ISSUE THREAD

**Issue by meganschauersnavex** [microsoftgraph/msgraph-search-connector-sample#15]
When attempting to run the app, I've opened my command-line interface (CLI) in the PartsInventoryConnector directory, and I've successfully ran "dotnet build."
However, when I attempt to use and "dotnet run" and I select "Create the connection," I receive the following error:

_"Code: generalException
Message: An error occurred sending the request."_

![image](https://user-images.githubusercontent.com/83420501/217843520-ea6a31ad-c193-403d-b73e-268326e1bbd4.png)

**Comment by finknotal** [comment]
Did you set the secret correctly?   Don't use the secret id - use the actual client secret value.

**Comment by jasonjoh** [comment]
I apologize for the lack of response. This sample was omitted from the list of samples to monitor and maintain. I suspect this error is due to the code being outdated. I'm going to be updating this sample in the next day or so with the latest dependencies, so hopefully that will clear up your issue.

**Comment by dviry** [comment]
still does not work - now throws a "400: InvalidRequest The request is malformed or incorrect." - any ideas?

**Comment by jasonjoh** [comment]
Yes - you cannot use a hyphen in the ID. From the [documentation](https://learn.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-1.0):

> Developer-provided unique ID of the connection within the Microsoft Entra tenant. Must be between 3 and 32 characters in length. Must only contain alphanumeric characters. Cannot begin with `Microsoft` or be one of the following values: `None`, `Directory`, `Exchange`, `ExchangeArchive`, `LinkedIn`, `Mailbox`, `OneDriveBusiness`, `SharePoint`, `Teams`, `Yammer`, `Connectors`, `TaskFabric`, `PowerBI`, `Assistant`, `TopicEngine`, `MSFT_All_Connectors`.
