### ISSUE TITLE
Deleting items

### ISSUE THREAD

**Issue by butchersoft1** [microsoftgraph/msgraph-search-connector-sample#2]
This is Great, and I plan to use the Graph helper library, but it appears to be missing the ability to delete items from the index.

Looking at the notes on the link below, my assumption is that it is the same code as "AddOrUpdateItem" without a body but with the PATCH method rather than PUT, however the HttpMethod does not support PATCH as outlined [here ](https://docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&tabs=http), so there is a bit more to it ?

not tested yet but something like

        public async Task DeleteItem(string connectionId, ExternalItem item)
        {
            var payload = JsonConvert.SerializeObject(item, _serializerSettings);

            var response = await PatchAsync(_graphClient, $"external/connections/{connectionId}/items/{item.Id}", null);
            return;

        }

        public static Task<HttpResponseMessage> PatchAsync(this HttpClient client, string requestUri, HttpContent content)
        {
            HttpRequestMessage request = new HttpRequestMessage
            {
                Method = new HttpMethod("PATCH"),
                RequestUri = new Uri(client.BaseAddress + requestUri),
                Content = content,
            };

            return client.SendAsync(request);
        }

Add PatchAsync to a separate class

**Comment by TekExpo** [comment]
AddorUpdateItem function is failing with below error message. This was working as expected and now it is failing with this message.

Code: generalException
Message: {
  "error": {
    "code": "BadRequest",
    "message": "Property content in payload has a value that does not match schema.",
    "innerError": {
      "request-id": "62cd9e15-feb3-48a3-bed7-a0a67f3e9661",
      "date": "2020-04-17T01:55:49"
    }
  }
}

**Comment by jasonjoh** [comment]
Latest version of the [Beta SDK](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet) has `DeleteAsync` for external items.
