### ISSUE TITLE
Maximum search results?

### ISSUE THREAD

**Issue by catmanjan** [microsoftgraph/msgraph-search-connector-sample#23]
I am setting the From parameter in my search to go through all results, but when I get to 1000 results I get an error that "BadRequestThe maximum allowed page size is 1000"

How do I page past 1000 items?

**Comment by jasonjoh** [comment]
Hi @catmanjan this isn't a good place to ask general Microsoft Graph how-to questions. There's a Microsoft Graph section on [Q&A](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) that is a better forum.
