### ISSUE TITLE
Error while creating externalItem

### ISSUE THREAD

**Issue by TekExpo** [microsoftgraph/msgraph-search-connector-sample#3]
AddorUpdateItem function is failing with below error message. This was working as expected and now it is failing with this message.

Code: generalException
Message: {
"error": {
"code": "BadRequest",
"message": "Property content in payload has a value that does not match schema.",
"innerError": {
"request-id": "62cd9e15-feb3-48a3-bed7-a0a67f3e9661",
"date": "2020-04-17T01:55:49"
}
}
}

**Comment by jasonjoh** [comment]
Thanks for reporting @TekExpo. This is due to a recent change to the `content` property, which is no longer a string. It's now an object like:

```
{
  "value": "This is the value",
  "type": "text"
}
```

Documentation is being updated to reflect this. I'll update the sample soon.

**Comment by TekExpo** [comment]
Thank you... :)

**Comment by jasonjoh** [comment]
Fixed this by converting to the SDK's built-in types. https://github.com/microsoftgraph/msgraph-search-connector-sample/commit/a54abc2c8bd2706db82d608ec1bd0842ed890f25
