### ISSUE TITLE
Missing ApplianceParts.csv file 

### ISSUE THREAD

**Issue by gretchunkim** [microsoftgraph/msgraph-search-connector-sample#46]
File is reference in this MS Documentation: https://learn.microsoft.com/en-us/samples/microsoftgraph/msgraph-search-connector-sample/microsoft-graph-search-connector-sample/ 

https://github.com/microsoftgraph/msgraph-search-connector-sample/blob/main/ApplianceParts.csv

**Comment by jasonjoh** [comment]
It may take a few days for the documentation page to pick up the change to the README.

**Comment by gretchunkim** [comment]
I see it now. Thanks!
