### ISSUE TITLE
The `property` object from microsoft.graph has updated `type` property for collection types

### ISSUE THREAD

**Issue by abhishek-raj** [microsoftgraph/msgraph-search-connector-sample#5]
The `property` object from microsoft.graph has updated `type` property for collection types.

They have changed to StringCollection, Int64Collection, DoubleCollection, DateTimeCollection

I get the following error when trying to Register the schema:

```json
Message: {
  "error": {
    "code": "InvalidRequest",
    "message": "The request is malformed or incorrect.",
    "innerError": {
      "code": "DeserializationError",
      "message": "Requested value 'Collection(String)' was not found.",
    }
  }
}
```

**Comment by jasonjoh** [comment]
Fixed this by using the SDK's built-in types. See https://github.com/microsoftgraph/msgraph-search-connector-sample/commit/a54abc2c8bd2706db82d608ec1bd0842ed890f25
